  language: perl
perl:
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.20.1"
  - "5.10"

sudo: false

before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init --auto
  
install:
  - cpanm --quiet --notest --skip-satisfied Dist::Zilla
  - dzil authordeps | grep -vP '[^\w:]' | cpanm --quiet --notest --skip-satisfied
  - dzil listdeps   | grep -vP '[^\w:]' | cpanm --verbose
script:
  - dzil smoke --release --author

notifications:
  recipients:
    - xlat@cpan.org
  email:
    on_success: change
    on_failure: always