language: perl
perl:
  - "blead"
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.20.1"
  - "5.10"
matrix:
  allow_failures:
    - perl: blead       # ignore failures for blead perl
#sudo: false
#Dzil config comes from https://github.com/mjgardner/svn-simple-hook/blob/master/.travis.yml
env: PERL_CPANM_OPT="--notest --force --skip-satisfied"
before_install:
  # bootstrap modules needed to manipulate dist
  - "cpanm --sudo Dist::Zilla"
  - "cpanm Pod::Coverage::TrustPod"
  # install dist development dependencies
  - "dzil authordeps | xargs cpanm"
  #not detected on blead
  - "cpanm Dist::Zilla::Plugin::PodWeaver"
  - "export tmpbuild=`mktemp --directory`"
  - "dzil build --in $tmpbuild"
  - "perl -MCPAN::Meta -e '$,=\"\\n\"; print CPAN::Meta->load_file(\"$ENV{tmpbuild}/META.json\")->effective_prereqs->requirements_for(\"develop\", \"requires\")->required_modules' | xargs cpanm"
install: "dzil listdeps | xargs cpanm"
script: "dzil test --release"

notifications:
  recipients:
    - xlat@cpan.org
  email:
    on_success: change
    on_failure: always